name: "modbus2mqtt"
description: "Service converts RTU and TCP Modbus to MQTT"
version: "1.0.0"
slug: "modbus2mqtt"
image: modbus2mqtt/modbus2mqtt
arch:
  - armv7
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services :
  - mqtt:want
map: 
  - share:rw
  - config:rw
  - ssl
ports:
  3000/tcp: null
ports_description: 
  3000/tcp: Frontend tcp-listen port
schema:
  data_path: str,
  mqtt:
    server": str?
    ca: str?
    key: str?
    cert: str?
    user: str?
    password: str?
  serial:
    port": str?
    baudrate: int?
image: modbus2mqtt/modbus2mqtt