name: "modbus2mqtt"
description: "Service converts RTU and TCP Modbus to MQTT"
version: "0.10.0"
slug: "modbus2mqtt"
image: modbus2mqtt/modbus2mqtt
arch:
  - armv7
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services :
  - mqtt:want
map: 
  - share:rw
  - config:rw
  - ssl:rw
ports:
  3000/tcp: null
ports_description: 
  3000/tcp: Frontend tcp-listen port
image: modbus2mqtt/modbus2mqtt
