name: "modbus2mqtt"
description: "Service converts RTU and TCP Modbus to MQTT from other"
version: "0.12.0"
slug: "modbus2mqtt"
arch:
  - armv7
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:want
map:
  - share:rw
  - config:rw
  - ssl:rw
ports:
  3000/tcp: 3000
  9229/tcp: 9229
ports_description:
  3000/tcp: Frontend tcp-listen port
hassio_api: true
hassio_role: default
homeassistant_api: true
host_network: true
auth_api: true
uart: true
image: modbus2mqtt/modbus2mqtt
