name: "Modbus <-> MQTT"
description: "Converter for both Directions: RTU and TCP Modbus to/from MQTT X"
version: "0.12.0"
slug: "modbus2mqtt"
arch:
  - aarch64
  - amd64
  - armv7
services:
  - mqtt:want
map:
  - share:rw
  - config:rw
  - ssl:rw
hassio_api: true
hassio_role: default
homeassistant_api: true
host_network: true
uart: true
webui: http://[HOST]:[PORT:3000]
panel_icon: mdi:arrow-left-right-bold-outline
init: false
ingress: true
ingress_port: 3000
ingress_stream: true
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
  max_old_space_size: int?
